spring:
  datasource:
    name: qyw
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #数据库配置
      url: jdbc:mysql:///peixunwang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true&useSSL=true
      username: root
      password: 1234
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      #      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          merge-sql: false
          slow-sql-millis: 20000
  redis:
    database: 1
    timeout: 5000
    # Redis服务器地址
    host: 47.107.136.229
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Redis1214
  profiles:
    active: dev

logging:
  config: classpath:logback-spring.xml

## mybatis独立节点
mybatis:
  mapper-locations: classpath:mapper/*.xml

